<div class="page-head"><div><h1>Data Kriteria</h1><p class="muted">Kelola kriteria yang dipakai dalam proses keputusan.</p></div></div>
<div class="grid-2">
    <div class="card panel"><h2>Tentang Kriteria</h2><p>Kriteria menjadi dasar penilaian menu MBG. Benefit berarti nilai makin tinggi makin baik; cost berarti nilai makin rendah makin baik.</p><div class="notice warning">Bobot kriteria diperoleh dari proses AHP, bukan diinput manual sebagai hasil akhir.</div></div>
    <div class="card panel"><h2>Bobot AHP Keseluruhan</h2><p>Total Konsistensi (CR) <strong class="text-green"><?= e(number_format((float) ($lastCr ?? 0), 3)) ?></strong></p>
        <?php foreach ($criteria as $criterion): $weight = (float) $criterion['bobot']; ?><p><?= e($criterion['kode'] . ' - ' . $criterion['nama']) ?> <span style="float:right"><strong><?= $weight > 0 ? e(number_format($weight, 3)) . ' (' . e(number_format($weight * 100, 2)) . '%)' : 'Belum dihitung' ?></strong></span><br><progress max="1" value="<?= e((string) $weight) ?>" style="width:75%"></progress></p><?php endforeach; ?>
    </div>
</div>
<div class="grid-2" style="grid-template-columns:1.5fr .7fr;margin-top:20px">
    <div class="card panel"><h2>Daftar Kriteria</h2>
        <?php if (!$criteria): ?>
            <?php $title='Belum ada data kriteria.'; $message='Tambahkan kriteria terlebih dahulu sebelum menjalankan AHP dan SAW.'; require app_path('views/components/empty-state.php'); ?>
        <?php else: ?>
        <div class="table-wrap"><table class="data-table"><thead><tr><th>Kode</th><th>Nama</th><th>Jenis</th><th>Bobot</th><th>Deskripsi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
        <?php foreach ($criteria as $criterion): $weight = (float) $criterion['bobot']; ?><tr><td><strong><?= e($criterion['kode']) ?></strong></td><td><?= e($criterion['nama']) ?></td><td><span class="badge <?= $criterion['jenis'] === 'cost' ? 'orange' : 'green' ?>"><?= e(ucfirst($criterion['jenis'])) ?></span></td><td><?= $weight > 0 ? e(number_format($weight, 3)) . '<br><span class="muted">' . e(number_format($weight * 100, 2)) . '%</span>' : '<span class="badge orange">Belum dihitung</span>' ?></td><td><?= e($criterion['deskripsi']) ?></td><td><span class="badge <?= $criterion['status'] === 'aktif' ? 'green' : 'gray' ?>"><?= e(ucfirst($criterion['status'])) ?></span></td><td><details><summary>Edit</summary><form class="form-grid mini-form" method="post" action="<?= url('kriteria/update/' . $criterion['id_kriteria']) ?>" data-loading-text="Menyimpan..."><?= csrf_field() ?><input name="kode" value="<?= e($criterion['kode']) ?>"><input name="nama" value="<?= e($criterion['nama']) ?>"><select name="jenis"><option value="benefit">benefit</option><option value="cost" <?= $criterion['jenis'] === 'cost' ? 'selected' : '' ?>>cost</option></select><input name="bobot" type="number" step="0.001" min="0" max="1" value="<?= e($criterion['bobot']) ?>"><textarea name="deskripsi"><?= e($criterion['deskripsi']) ?></textarea><select name="status"><option value="aktif">aktif</option><option value="nonaktif" <?= $criterion['status'] === 'nonaktif' ? 'selected' : '' ?>>nonaktif</option></select><button class="btn btn-primary" type="submit">Simpan</button></form></details></td></tr><?php endforeach; ?>
    </tbody></table></div>
    <?php endif; ?>
    </div>
    <div class="card drawer"><h2>Tambah Kriteria</h2><form class="form-grid" method="post" action="<?= url('kriteria/store') ?>" data-loading-text="Menyimpan..."><?= csrf_field() ?>
        <label>Kode<input class="<?= e(field_error_class('kode')) ?>" name="kode" value="<?= e(old('kode')) ?>" placeholder="C6" required<?= field_error_attrs('kode') ?>><?= field_error_html('kode') ?></label>
        <label>Nama<input class="<?= e(field_error_class('nama')) ?>" name="nama" value="<?= e(old('nama')) ?>" required<?= field_error_attrs('nama') ?>><?= field_error_html('nama') ?></label>
        <label>Jenis<select class="<?= e(field_error_class('jenis')) ?>" name="jenis" required<?= field_error_attrs('jenis') ?>><option value="benefit" <?= old('jenis','benefit') === 'benefit' ? 'selected' : '' ?>>Benefit</option><option value="cost" <?= old('jenis') === 'cost' ? 'selected' : '' ?>>Cost</option></select><?= field_error_html('jenis') ?></label>
        <label>Bobot Manual<input class="<?= e(field_error_class('bobot')) ?>" name="bobot" type="number" step="0.001" min="0" max="1" value="<?= e(old('bobot','0')) ?>" required<?= field_error_attrs('bobot') ?>><?= field_error_html('bobot') ?><span class="field-help">Total bobot aktif idealnya mendekati 1.000.</span></label>
        <label>Deskripsi<textarea name="deskripsi"><?= e(old('deskripsi')) ?></textarea></label>
        <label>Status<select class="<?= e(field_error_class('status')) ?>" name="status" required<?= field_error_attrs('status') ?>><option value="aktif" <?= old('status','aktif') === 'aktif' ? 'selected' : '' ?>>Aktif</option><option value="nonaktif" <?= old('status') === 'nonaktif' ? 'selected' : '' ?>>Nonaktif</option></select><?= field_error_html('status') ?></label><button class="btn btn-primary" type="submit">Simpan Kriteria</button></form></div>
</div>
