<?php $hasRankings = !empty($rankings); ?>
<form class="toolbar" method="get" action="<?= url('laporan') ?>" data-loading-text="Menampilkan laporan...">
    <input class="input" type="date" name="periode_dari" value="<?= e($period['from'] ?? date('Y-m-01')) ?>" required>
    <input class="input" type="date" name="periode_sampai" value="<?= e($period['to'] ?? date('Y-m-d')) ?>" required>
    <select class="select"><option>Semua Menu</option></select>
    <button class="btn btn-primary" type="submit">Tampilkan Laporan</button>
    <?php if ($hasRankings): ?>
        <a class="btn btn-outline" href="<?= url('laporan/pdf') ?>?periode_dari=<?= e($period['from'] ?? date('Y-m-01')) ?>&periode_sampai=<?= e($period['to'] ?? date('Y-m-d')) ?>" data-loading-link>Download PDF</a>
        <a class="btn btn-outline" href="<?= url('laporan/excel') ?>?periode_dari=<?= e($period['from'] ?? date('Y-m-01')) ?>&periode_sampai=<?= e($period['to'] ?? date('Y-m-d')) ?>" data-loading-link>Download Excel</a>
    <?php else: ?>
        <button class="btn btn-outline is-disabled" type="button" disabled>Download PDF</button>
        <button class="btn btn-outline is-disabled" type="button" disabled>Download Excel</button>
    <?php endif; ?>
</form>
<div class="grid-2" style="grid-template-columns:1.6fr .7fr">
    <div>
        <div class="card panel"><h2>LAPORAN HASIL ANALISIS SPK MBG</h2><p>Metode AHP - SAW</p><div class="grid-4"><div><b>Periode</b><br><?= e($period['from'] ?? date('Y-m-01')) ?> - <?= e($period['to'] ?? date('Y-m-d')) ?></div><div><b>Tanggal Cetak</b><br><?= date('d M Y H:i') ?> WIB</div><div><b>Dicetak Oleh</b><br><?= e(current_user()['username'] ?? 'Admin') ?></div><div><b>Total Ranking</b><br><?= count($rankings) ?> Menu</div></div></div>
        <?php if (!$rankings): ?>
            <div class="card panel" style="margin-top:20px"><?php $title='Belum ada hasil ranking.'; $message='Hitung SAW terlebih dahulu.'; require app_path('views/components/empty-state.php'); ?></div>
        <?php else: ?>
        <div class="grid-2" style="margin-top:20px"><div class="card panel"><h2>Rekomendasi Menu Terbaik</h2><div class="food-illus"></div><h3><?= e($rankings[0]['nama_menu'] ?? 'Belum ada hasil') ?></h3><h1 class="text-green"><?= e(number_format((float) ($rankings[0]['nilai_vi'] ?? 0), 3)) ?></h1></div><div class="card panel"><h2>Top Ranking Menu</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Ranking</th><th>Kode</th><th>Nama Menu</th><th>Nilai Vi</th></tr></thead><tbody><?php foreach ($rankings as $row): ?><tr><td><strong><?= e($row['ranking']) ?></strong></td><td><?= e($row['kode']) ?></td><td><?= e($row['nama_menu']) ?></td><td><strong><?= e(number_format((float) $row['nilai_vi'], 3)) ?></strong></td></tr><?php endforeach; ?></tbody></table></div></div></div>
        <div class="grid-2" style="margin-top:20px"><div class="card panel"><h2>Data Kriteria dan Bobot AHP</h2><p>Nilai CR <strong class="text-green" style="float:right"><?= e(number_format((float) ($latestCr ?? 0), 4)) ?></strong></p><div class="table-wrap"><table class="data-table"><thead><tr><th>Kode</th><th>Kriteria</th><th>Jenis</th><th>Bobot</th></tr></thead><tbody><?php foreach ($criteria as $criterion): ?><tr><td><strong><?= e($criterion['kode']) ?></strong></td><td><?= e($criterion['nama']) ?></td><td><span class="badge <?= $criterion['jenis'] === 'cost' ? 'orange' : 'green' ?>"><?= e(ucfirst($criterion['jenis'])) ?></span></td><td><?= e(number_format((float) $criterion['bobot'], 3)) ?> <span class="muted">(<?= e(number_format((float) $criterion['bobot'] * 100, 2)) ?>%)</span></td></tr><?php endforeach; ?></tbody></table></div></div><div class="card panel"><h2>Kesimpulan Rekomendasi</h2><p>Berdasarkan bobot AHP dan nilai preferensi SAW, menu terbaik pada periode ini adalah:</p><h3><?= e($rankings[0]['kode'] ?? '-') ?> - <?= e($rankings[0]['nama_menu'] ?? '-') ?></h3><p>Nilai Vi <strong class="text-green"><?= e(number_format((float) ($rankings[0]['nilai_vi'] ?? 0), 3)) ?></strong>. Menu dengan nilai Vi tertinggi menjadi rekomendasi utama program MBG.</p></div></div>
        <?php endif; ?>
        <div class="card panel" style="margin-top:20px"><h2>Riwayat Download Laporan</h2><?php if (!$history): ?><?php $title='Belum ada riwayat export.'; $message='Riwayat akan muncul setelah laporan PDF/Excel disiapkan.'; require app_path('views/components/empty-state.php'); ?><?php else: ?><div class="table-wrap"><table class="data-table"><thead><tr><th>Tanggal</th><th>Admin</th><th>Menu Terbaik</th><th>Nilai Vi</th><th>File</th></tr></thead><tbody><?php foreach ($history as $row): ?><tr><td><?= e($row['tanggal']) ?></td><td><?= e($row['admin']) ?></td><td><?= e($row['menu_terbaik']) ?></td><td><?= e(number_format((float) $row['nilai_vi'], 3)) ?></td><td><span class="badge orange"><?= e($row['file_path']) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
    </div>
    <aside><div class="card panel"><h2>Ekspor Laporan</h2><label><input type="radio" checked> Ringkasan Eksekutif</label><br><label><input type="radio"> Laporan Lengkap</label><br><label><input type="radio"> Detail per Menu</label><hr><label><input type="checkbox" checked> Sertakan Grafik</label><br><label><input type="checkbox" checked> Sertakan Tabel Detail</label><br><label><input type="checkbox" checked> Penjelasan Metodologi</label><br><?php if ($hasRankings): ?><a class="btn btn-primary" style="width:100%;margin-top:18px" href="<?= url('laporan/pdf') ?>?periode_dari=<?= e($period['from'] ?? date('Y-m-01')) ?>&periode_sampai=<?= e($period['to'] ?? date('Y-m-d')) ?>" data-loading-link>Download Laporan</a><?php else: ?><button class="btn btn-primary is-disabled" style="width:100%;margin-top:18px" type="button" disabled>Download Laporan</button><p class="muted">Hitung SAW terlebih dahulu untuk membuka export.</p><?php endif; ?></div><div class="card panel" style="margin-top:20px"><h2>Status Export</h2><p class="muted">Export PDF/Excel saat ini berupa placeholder siap diintegrasikan dengan mPDF/TCPDF dan PhpSpreadsheet.</p></div></aside>
</div>
